### ISSUE TITLE
Merge web3 library into this one 

### ISSUE THREAD

**Issue by jtremback** [althea-net/clarity#67]
I think that these two libraries could benefit from being developed as a unified tool to work with Ethereum. We may end up splitting them back up at some point, but I think it's useful for now to have them together. I think it will be uncommon for people to work with one but not the other.

**Comment by gakonst** [comment]
Definitely a good idea to merge https://github.com/althea-net/guac_rs/tree/master/web3 with this.

**Comment by jkilpatr** [comment]
Did this.
